USE GeneralExcel_DB;

CREATE TABLE GeneralExcel_DB.dbo.tabAppPrint ( RepID int NOT NULL, PrintFormat nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabAppPr__2F6FA9AB50CC8991 PRIMARY KEY (RepID) );

CREATE TABLE GeneralExcel_DB.dbo.tabAutoBM ( RuleID int NULL, sFormat nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iSerial int NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabAutoFill ( RepID int NOT NULL, sTimeSetting varchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sLastDoTime datetime NULL, DoDate datetime NULL, CONSTRAINT PK__tabAutoF__2F6FA9AB65BA253B PRIMARY KEY (RepID) );

CREATE TABLE GeneralExcel_DB.dbo.tabBOMSDR ( bomID int NOT NULL, FieldID varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, DataRule int NULL, ExFillField varchar(200) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabBaseTableDataLocked ( tabID int NOT NULL, CONSTRAINT PK__tabBaseT__50656ECADDE7426C PRIMARY KEY (tabID) );

CREATE TABLE GeneralExcel_DB.dbo.tabBom ( bomID int NOT NULL, sBM nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, iCreator int NOT NULL, bNMOther char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iMaxLevel int DEFAULT 0 NOT NULL, sColor varchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabBom__B6B0886830E01786 PRIMARY KEY (bomID) );

CREATE TABLE GeneralExcel_DB.dbo.tabBomNodeType ( bomID int NULL, iNodeTypeID int NULL, sDisplayField varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sMainFieldID int NULL, sLevelBMFieldID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sBOMIDFieldID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, slstFieldID varchar(600) COLLATE Chinese_PRC_CI_AS NULL, slstFieldName nvarchar(600) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabBomTree ( bomID int NULL, DataID int NULL, iNodeID int NULL, iNodeTypeID int NULL, sLevelNo varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sNodeName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsLeaf char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iFromDataID int DEFAULT 0 NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabCAdminR ( iID int NOT NULL, sValue char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iImageIndex int NOT NULL, RoleID int NOT NULL, iID2 int NOT NULL, iOrd int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabCancelTaskFormula ( RepID int NOT NULL, DataID int NOT NULL, sFormula text COLLATE Chinese_PRC_CI_AS NULL, sLinkID varchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabCategory ( CatID int NOT NULL, sName nvarchar(60) COLLATE Chinese_PRC_CI_AS NOT NULL, SJ int NULL, sBM nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabCateg__6A1C8ADA038508B1 PRIMARY KEY (CatID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable ( tabID int NOT NULL, tabName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, bBase int NULL, FormHeight int NULL, FormWidth int NULL, FormFormat image NULL, sOriTabName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sSchema nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDataFL varchar(300) COLLATE Chinese_PRC_CI_AS NULL, sDataOrd varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CatID int DEFAULT -1 NOT NULL, sBM varchar(30) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, sName2 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabDIYTa__50656ECA2B4BC377 PRIMARY KEY (tabID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable0 ( F1 char(10) COLLATE Chinese_PRC_CI_AS NOT NULL, CONSTRAINT PK__tabDIYTa__321492706CE0272A PRIMARY KEY (F1) );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable1 ( ID int NOT NULL, F1 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabDIYTa__3214EC27BE9DF158 PRIMARY KEY (ID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable2 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F2 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F3 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F4 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F5 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F6 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F7 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable3 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F8 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F9 datetime DEFAULT '' NOT NULL, F10 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F11 numeric(20, 0) DEFAULT 0 NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable4 ( ID int NOT NULL, iOrd int NOT NULL, F12 numeric(20, 0) DEFAULT 0 NOT NULL, F13 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F14 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F15 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F16 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F17 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F18 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F19 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F20 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F21 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F22 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable999998011 ( ID int NOT NULL, F999991001 varchar(3000) COLLATE Chinese_PRC_CI_AS NULL, F999991002 nvarchar(1500) COLLATE Chinese_PRC_CI_AS NULL, SendedDate datetime DEFAULT '' NOT NULL, F999991003 int DEFAULT 0 NOT NULL, F999991005 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable999998012 ( ID int NOT NULL, F999991011 varchar(200) COLLATE Chinese_PRC_CI_AS NULL, F999991012 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, F999991013 nvarchar(1500) COLLATE Chinese_PRC_CI_AS NULL, F999991015 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991016 int DEFAULT 0 NOT NULL, F999991017 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable999998036 ( ID int NOT NULL, F999991166 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991168 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTable999998038 ( iID int NULL, F999991126 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991128 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991132 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, F999991136 datetime NULL, F999991138 datetime NULL, F999991137 int DEFAULT 0 NOT NULL, F999991139 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTableField ( tabID int NOT NULL, fieldID int NOT NULL, fieldName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iRow int NULL, iCol int NULL, TypeID int NOT NULL, bUnique char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bRequire char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bComboUnique char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, DataRule int NOT NULL, ParameterField varchar(500) COLLATE Chinese_PRC_CI_AS NULL, bNoClearData char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL, sOriFieldName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sOriFieldType varchar(50) COLLATE Chinese_PRC_CI_AS NULL, NoDisplay char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanKeyInput char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanSelAtRule char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bCanModifyAtFillDataWithFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bCanSelAtFillDataWithFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, ExFillField varchar(800) COLLATE Chinese_PRC_CI_AS NULL, bCanModifyExcelFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sLinkRepData ntext COLLATE Chinese_PRC_CI_AS NULL, sHintUnique nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sHintEmpty nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bAlwaysShowSelWin char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMerge char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sPicFileCon varchar(50) COLLATE Chinese_PRC_CI_AS NULL, bNF char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sCHK varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sName2 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, sReferF int DEFAULT 0 NOT NULL, CONSTRAINT PK__tabDIYTa__F0AC27FE8E5AE6E3 PRIMARY KEY (fieldID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTableFieldM ( NaviID int NOT NULL, ItemID int NOT NULL, tabID int NOT NULL, FieldID int NOT NULL, FieldName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sGroup nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bDisp int NOT NULL, bDigest int NOT NULL, iRowCount int NOT NULL, iOrd int NOT NULL, iOrd2 int NOT NULL, iColWidth int NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDIYTableFieldMW ( NaviID int NOT NULL, ItemID int NOT NULL, tabID int NOT NULL, iObjType int NOT NULL, FieldID int NOT NULL, FieldName nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sGroup nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bDisp int NOT NULL, bDigest int NOT NULL, iRowCount varchar(10) COLLATE Chinese_PRC_CI_AS NOT NULL, iMargin int NOT NULL, iRow int NOT NULL, iRWidth int NOT NULL, iRMargin int NOT NULL, iLabPos int NOT NULL, sLabWidth varchar(10) COLLATE Chinese_PRC_CI_AS NULL, sHint nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iTouch int NULL, sParam nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NOT NULL, iOrd2 int NOT NULL, sTotal nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, iColWidth int NULL, iCard int DEFAULT 0 NULL, iNC int DEFAULT 0 NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDV ( iID int NULL, sName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iOperType int NOT NULL, iObjType int NOT NULL, iObjID int NOT NULL, iRepID int NOT NULL, iCreator int NOT NULL, iUser int NOT NULL, bDefault char(1) COLLATE Chinese_PRC_CI_AS NULL, bCanEdit char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDVs ( iID int NOT NULL, iUser int NOT NULL, TabID int NOT NULL, FieldID varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, bVisible char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iWidth int NOT NULL, sTotal nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, bSys char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDataRule ( RuleID int NOT NULL, RuleName nvarchar(60) COLLATE Chinese_PRC_CI_AS NOT NULL, RuleType int NOT NULL, DataSrc char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, MultiSel char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, OnlyLeaf char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bOrigin char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bUnique char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bReFresh char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMayNULL char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoAutoFit char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iCreator int DEFAULT 0 NOT NULL, bNMOther char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bFOBO char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sSize varchar(20) COLLATE Chinese_PRC_CI_AS NULL, bQuery char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sDisN varchar(40) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int DEFAULT 0 NULL, CONSTRAINT PK__tabDataR__110458C25B006E58 PRIMARY KEY (RuleID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDataRuleCategory ( CatID int NOT NULL, sName nvarchar(25) COLLATE Chinese_PRC_CI_AS NOT NULL, SJ int NOT NULL, sNameB nvarchar(25) COLLATE Chinese_PRC_CI_AS NULL, sNameC nvarchar(25) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabDataR__6A1C8ADABBA53805 PRIMARY KEY (CatID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDataRules1 ( RuleID int NOT NULL, ValueID int NOT NULL, SubValue nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, LevelValue varchar(30) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDataRules2 ( RuleID int NOT NULL, tabIDName varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, DisplayField varchar(500) COLLATE Chinese_PRC_CI_AS NOT NULL, ConditionNames ntext COLLATE Chinese_PRC_CI_AS NULL, LevelField nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, LevelLen varchar(30) COLLATE Chinese_PRC_CI_AS NULL, OrdField varchar(150) COLLATE Chinese_PRC_CI_AS NULL, bIsDESC varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, ValueFieldIndex int DEFAULT 0 NOT NULL, sCategory varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sTree3 varchar(200) COLLATE Chinese_PRC_CI_AS NULL, NDispF varchar(500) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(300) COLLATE Chinese_PRC_CI_AS NULL, ConditionIDs ntext COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDataRules3 ( RuleID int NOT NULL, HeadTitle nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL, DateFormat varchar(8) COLLATE Chinese_PRC_CI_AS NULL, SerialLen int NULL, StartValue int NULL, ResetAfterDateChange char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, DateValue varchar(8) COLLATE Chinese_PRC_CI_AS NULL, SerialValue int NULL, ActionAfterSave char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, ReuseType char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, TitleAfterDate varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sFormat nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, sFormatSetting nvarchar(150) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, NFN char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabDataSrcOther ( srcID int NOT NULL, srcName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sAccessPrefix nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sProvider varchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDataSrc nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDBName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sLoginUser nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sPassword varchar(30) COLLATE Chinese_PRC_CI_AS NULL, bCanModify char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, CONSTRAINT PK__tabDataS__5DD08E2F08FD9B63 PRIMARY KEY (srcID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDataType ( TypeID int NOT NULL, TypeName nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, OriginType varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, iLen int NOT NULL, iXSLen int NULL, sDefault varchar(20) COLLATE Chinese_PRC_CI_AS NULL, MatchWord nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, iOrd int DEFAULT 0 NULL, CONSTRAINT PK__tabDataT__516F03959233D629 PRIMARY KEY (TypeID) );

CREATE TABLE GeneralExcel_DB.dbo.tabDepartment ( DeptID int NOT NULL, sName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, BM nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, SJ int NOT NULL, FZJG char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, CONSTRAINT PK__tabDepar__0148818ED9F465A7 PRIMARY KEY (DeptID) );

CREATE TABLE GeneralExcel_DB.dbo.tabEMAILSended ( iID int NOT NULL, dSendDT datetime NULL, sAddress varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sSubject nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sContent nvarchar(1500) COLLATE Chinese_PRC_CI_AS NULL, sAttchFile nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabEMAIL__DC512D72A8F2954A PRIMARY KEY (iID) );

CREATE TABLE GeneralExcel_DB.dbo.tabEntFlow ( EntFlowID int NOT NULL, bUse char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, date1 datetime NOT NULL, date2 datetime NOT NULL, iAfter int DEFAULT 0 NOT NULL, FlowID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, OperID1 int NOT NULL, OperID2 varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabEntFl__DCE624BD6F22CF06 PRIMARY KEY (EntFlowID) );

CREATE TABLE GeneralExcel_DB.dbo.tabEnterprise ( EnterID int NOT NULL, sName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, Address nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, PostNo varchar(20) COLLATE Chinese_PRC_CI_AS NULL, Tel varchar(20) COLLATE Chinese_PRC_CI_AS NULL, Fex varchar(20) COLLATE Chinese_PRC_CI_AS NULL, email varchar(30) COLLATE Chinese_PRC_CI_AS NULL, www varchar(100) COLLATE Chinese_PRC_CI_AS NULL, Bank nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL, CountNo varchar(30) COLLATE Chinese_PRC_CI_AS NULL, TaxNo varchar(30) COLLATE Chinese_PRC_CI_AS NULL, CheckDay int NULL, CONSTRAINT PK__tabEnter__74B398144E653561 PRIMARY KEY (EnterID) );

CREATE TABLE GeneralExcel_DB.dbo.tabFTPPicFile ( RepID int NOT NULL, DataID int NOT NULL, sFileName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFillRule ( FormulaID int NOT NULL, TabID int NOT NULL, SrcFieldSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, SrcFieldSM nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL, FillType int NOT NULL, TargetFieldID int NOT NULL, iOrd int NOT NULL, sQryFName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sFlag char(1) COLLATE Chinese_PRC_CI_AS NULL, sTotal nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, iOrd2 int DEFAULT 0 NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlow ( flowID int NOT NULL, RepID int NOT NULL, flowCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, bValidate char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, chart image NOT NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, PauseField varchar(20) COLLATE Chinese_PRC_CI_AS NULL, [NoLock] char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sSubject nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sFormula varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, bNotInNoF int DEFAULT 0 NOT NULL, CONSTRAINT PK__tabFlow__A94CE37DCE89CA7A PRIMARY KEY (flowID) );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowLink ( FlowID int NOT NULL, LinkID varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, BeginTaskID int NOT NULL, EndTaskID int NOT NULL, bNewRep char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NewRepID int NULL, ConditionType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ConditionsSQL ntext COLLATE Chinese_PRC_CI_AS NULL, ConditionsSM ntext COLLATE Chinese_PRC_CI_AS NULL, lstFormulaID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, sHint nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, NewRepFirstDoUser varchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '0,0' NOT NULL, sClearFieldP varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sClearFieldB varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sFillField varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, bAsBack char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, DoUser char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, lstDeptID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, lstRoleID varchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowMS ( FlowID int NULL, FlowPostID int NULL, DataID int NULL, taskID int NULL, iOrd numeric(13, 4) NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sSubject nvarchar(600) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowPost ( RepID int NOT NULL, FlowID int NOT NULL, FlowPostID int NOT NULL, DataID int NOT NULL, taskID int NOT NULL, DoTime datetime NOT NULL, DoUser int NOT NULL, iOrd numeric(20, 4) NOT NULL, iState smallint NOT NULL, DoingUser int NOT NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iHA int DEFAULT 0 NOT NULL, iHAValues nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, iDoLevel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iSub int DEFAULT 0 NOT NULL, DoTime1 datetime DEFAULT '0' NOT NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowPostF ( RepID int NOT NULL, FlowID int NOT NULL, FlowPostID int NOT NULL, DataID int NOT NULL, taskID int NOT NULL, DoTime datetime NOT NULL, DoUser int NOT NULL, iOrd numeric(20, 4) NOT NULL, iState smallint NOT NULL, DoingUser int NOT NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iHA int DEFAULT 0 NOT NULL, iHAValues nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, iDoLevel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iSub int DEFAULT 0 NOT NULL, DoTime1 datetime DEFAULT '0' NOT NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowPostS ( RepID int NOT NULL, FlowID int NOT NULL, FlowPostID int NOT NULL, DataID int NOT NULL, taskID int NOT NULL, DoTime datetime NOT NULL, DoUser int NOT NULL, iOrd numeric(20, 4) NOT NULL, iState smallint NOT NULL, DoingUser int NOT NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iHA int DEFAULT 0 NOT NULL, iHAValues nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, iDoLevel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iSub int DEFAULT 0 NOT NULL, DoTime1 datetime DEFAULT '0' NOT NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowTask ( flowID int NOT NULL, taskID int NOT NULL, taskCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, bSaveDataAfterFinish char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bIsMustDoBeforeTime char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, MustDoBeforeTime int NOT NULL, TimeUnit char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, DoUser varchar(3) COLLATE Chinese_PRC_CI_AS NULL, ExeType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, lstFormulaID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, FillArea varchar(3500) COLLATE Chinese_PRC_CI_AS NULL, lstDeptID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, lstRoleID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, bCanViewAfterDo char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sHintSet varchar(100) COLLATE Chinese_PRC_CI_AS NULL, bUseEMail char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bUseSMS char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoVisiArea varchar(1500) COLLATE Chinese_PRC_CI_AS NULL, NoPause char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoPrior varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, NoCancel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoCheck char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanTran varchar(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOther varchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowTaskHAL ( FlowID int NOT NULL, FlowPostID int NOT NULL, iTime int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFlowTaskRuleForNewRepFlow ( FlowID int NOT NULL, LinkID varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, srcRepTable int NOT NULL, srcFieldID int NOT NULL, FillType varchar(10) COLLATE Chinese_PRC_CI_AS NOT NULL, destRepTable int NOT NULL, destFieldID int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFormula ( RepID int NOT NULL, FormulaID int NOT NULL, FormulaName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, FormulaType int NOT NULL, ExeTime varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL, UseShortCut char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ClearFillRange char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ResultIsUnique char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, OrdType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, SrcTabID varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, SelTemp char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NULL, bSomeData char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, SomeRecords int DEFAULT 0 NOT NULL, bAppendData char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sWhereSQL2 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sWhereSM2 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, bIncludeNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sHintYes nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sHintNo nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, ResultAction char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoDisplayTextWhenApply char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bDelNullRowAfterExecute char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sToDoUser varchar(200) COLLATE Chinese_PRC_CI_AS NULL, bReFreshSheet char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoCheckRelation char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bAppendWhenNoMatch char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOrderAfterExec varchar(30) COLLATE Chinese_PRC_CI_AS NULL, sMergeField varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, bUnMerge char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoFill0 char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bShowWait char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, ReserveRowCol int DEFAULT 0 NOT NULL, iVer int DEFAULT 0 NOT NULL, sSysRule varchar(200) COLLATE Chinese_PRC_CI_AS NULL, bDSOther char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iMPP char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoAuto char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL3 ntext COLLATE Chinese_PRC_CI_AS NULL, sWhereSM3 ntext COLLATE Chinese_PRC_CI_AS NULL, FormulaSM ntext COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL ntext COLLATE Chinese_PRC_CI_AS NULL, sWhereSM ntext COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFormulaGrid ( FID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFormulaWithSSFunction ( FID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, sFormula nvarchar(500) COLLATE Chinese_PRC_CI_AS NOT NULL, SheetName nvarchar(80) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabFunction ( CatID int NOT NULL, CatName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, Flag char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iOrd int NULL, CONSTRAINT PK__tabFunct__9C61AB27723959BC PRIMARY KEY (CatName) );

CREATE TABLE GeneralExcel_DB.dbo.tabFunctions ( CatID int NOT NULL, FuncName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, FuncSQL varchar(130) COLLATE Chinese_PRC_CI_AS NOT NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NOT NULL, CONSTRAINT PK__tabFunct__10105C80756F178E PRIMARY KEY (FuncName) );

CREATE TABLE GeneralExcel_DB.dbo.tabGVar ( iID int NOT NULL, sVarName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sVarValue nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabGridFormat ( RepID int NOT NULL, DataID int NOT NULL, tabID int NOT NULL, FieldID int NOT NULL, iRow int DEFAULT 0 NOT NULL, iCol int DEFAULT 0 NOT NULL, iRowCount int DEFAULT 0 NOT NULL, iColCount int DEFAULT 0 NOT NULL, sSetting nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabGridTextOfFormat ( FID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, sText nvarchar(500) COLLATE Chinese_PRC_CI_AS NOT NULL, SheetName nvarchar(80) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabHyperLinks ( RepID int NOT NULL, DataID int NOT NULL, TabID int NOT NULL, FieldID int NOT NULL, iRelativeRow int NOT NULL, iRelativeCol int NOT NULL, sFileName nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, fFile image NOT NULL, sLinkNo varchar(20) COLLATE Chinese_PRC_CI_AS NULL, bFTP char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabInnerTableCode ( iTabID int NOT NULL, sCode text COLLATE Chinese_PRC_CI_AS NULL, iFormulaID int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabLockRepDataFormula ( RepID int NOT NULL, sFormulaSM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sFormulaSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, bUnLock char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bOnlyThis char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, CONSTRAINT PK__tabLockR__2F6FA9AB8066E1DC PRIMARY KEY (RepID) );

CREATE TABLE GeneralExcel_DB.dbo.tabLog ( OperUserName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, OperTime varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, sIP nvarchar(150) COLLATE Chinese_PRC_CI_AS NOT NULL, FuncName nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, SM nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabLoginByOther ( bActived char(1) COLLATE Chinese_PRC_CI_AS NULL, sURL nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sUser nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sPwd varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sResult nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sResultValue nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL, sMsg nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabLoginInfo ( sLoginUser varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sLoginName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sLoginIP nvarchar(150) COLLATE Chinese_PRC_CI_AS NULL, tLoginTime datetime NULL, iOnlineMinute int NULL, InterLoginID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sDBName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sLocalIPAndName nvarchar(150) COLLATE Chinese_PRC_CI_AS NULL, sLoginUser2 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabLoginLog ( OperID int NOT NULL, ChPWDateTime datetime NULL, LockTime datetime NULL, sLastPW text COLLATE Chinese_PRC_CI_AS NULL, sPWErrLog ntext COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabLogin__F288E41DFB77E1B0 PRIMARY KEY (OperID) );

CREATE TABLE GeneralExcel_DB.dbo.tabMFValues ( RepID int NOT NULL, DataID int NOT NULL, TabID int NOT NULL, FieldID int NOT NULL, iOrd int NOT NULL, sValue nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabNULL ( a1 char(1) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabNaviItem ( ItemID int NOT NULL, NaviID int NOT NULL, sCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iAction int NOT NULL, iObj int NOT NULL, iOrd int NOT NULL, imgIcon image NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, iFlowID int DEFAULT 0 NULL, CONSTRAINT PK__tabNaviI__727E83EBFBCFF2A1 PRIMARY KEY (ItemID) );

CREATE TABLE GeneralExcel_DB.dbo.tabNaviM ( NaviID int NOT NULL, NaviCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL, iFlag int DEFAULT 0 NOT NULL, sVer varchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NaviBM varchar(20) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabNaviM__2F08BDA8CA299615 PRIMARY KEY (NaviID) );

CREATE TABLE GeneralExcel_DB.dbo.tabNavigate ( NaviID int NOT NULL, NaviBM nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL, NaviCaption nvarchar(80) COLLATE Chinese_PRC_CI_AS NULL, NaviVer varchar(20) COLLATE Chinese_PRC_CI_AS NULL, DisTab varchar(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NaviPic image NULL, NaviIcon image NULL, TopTab char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCheckQX char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabNavig__2F08BDA84CA12AF2 PRIMARY KEY (NaviID) );

CREATE TABLE GeneralExcel_DB.dbo.tabNoVF ( FID int NOT NULL, dtID int NOT NULL, FieldID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, iEndRow int NOT NULL, iEndCol int NOT NULL, iLayoutType int NOT NULL, SheetName nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabObjDoing ( iObjType int NULL, iObjID int NULL, iOperID int NULL, sOperName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, dOperDate datetime NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabOperator ( OperID int NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, DeptID int NOT NULL, LoginName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, LoginPassword varchar(200) COLLATE Chinese_PRC_CI_AS NULL, Mobile varchar(20) COLLATE Chinese_PRC_CI_AS NULL, email varchar(100) COLLATE Chinese_PRC_CI_AS NULL, SJType int NOT NULL, SJDepartment int NULL, SJRole int NULL, SJOperator int NULL, BZ1 char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, SM nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sIP varchar(100) COLLATE Chinese_PRC_CI_AS NULL, bLock char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sDeptAdmin varchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, bMLog char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoChPW char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sLogF varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sOrd nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabOpera__F288E41D99B2E2FA PRIMARY KEY (OperID) );

CREATE TABLE GeneralExcel_DB.dbo.tabOption ( OperID int NOT NULL, OptionName varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, OptionValue varchar(30) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabOtherSrcTable ( tabID int NOT NULL, sPrefix nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sStruct ntext COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabOther__50656ECA91978F26 PRIMARY KEY (tabID) );

CREATE TABLE GeneralExcel_DB.dbo.tabPZ ( RepID int NOT NULL, DataID int NOT NULL, tabID int NOT NULL, FieldID int NOT NULL, iRow int NULL, iCol int NULL, sPZ nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabPrintSetting ( RepID int NOT NULL, bSave char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bConField char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sField varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sMsg nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iPrtTimes int DEFAULT 0 NOT NULL, sMsgT nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabPrint__2F6FA9AB2F29853F PRIMARY KEY (RepID) );

CREATE TABLE GeneralExcel_DB.dbo.tabPrtLog ( RepID int NULL, DataID int NULL, sLoginName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sDateTime datetime NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabQX ( ObjID int NOT NULL, lstDeptID varchar(3000) COLLATE Chinese_PRC_CI_AS NULL, lstRoleID varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, lstOperID varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, QXType int NOT NULL, ObjType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabQX1 ( QXID int NOT NULL, ObjID int NOT NULL, iDeptID int NOT NULL, iRoleID int NOT NULL, iOperID int NOT NULL, QXType int NOT NULL, ObjType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NoVisibleFieldIDs varchar(3000) COLLATE Chinese_PRC_CI_AS NULL, QXTypeByContent char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, QXField varchar(20) COLLATE Chinese_PRC_CI_AS NULL, QXType2 int DEFAULT 0 NOT NULL, QXConst nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sWhereSM nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL2 nvarchar(700) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQX1__F530AB3F3CD6FC72 PRIMARY KEY (QXID) );

CREATE TABLE GeneralExcel_DB.dbo.tabQX2 ( QXID int NOT NULL, RepID int NOT NULL, TabID int NOT NULL, iDeptID int NOT NULL, iRoleID int NOT NULL, iOperID int NOT NULL, CONSTRAINT PK__tabQX2__F530AB3FDDF2A8FA PRIMARY KEY (QXID) );

CREATE TABLE GeneralExcel_DB.dbo.tabQX3 ( QXID int NOT NULL, ObjID int NOT NULL, iDeptID int NOT NULL, iRoleID int NOT NULL, QXType int NOT NULL, ManageType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, CONSTRAINT PK__tabQX3__F530AB3F79C0DDB5 PRIMARY KEY (QXID) );

CREATE TABLE GeneralExcel_DB.dbo.tabQXEdit ( QXID int NOT NULL, ObjID int NOT NULL, bOnlyMe char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bMe char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bNoMe char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bOther char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, slstOtherOper varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ObjType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, slstDept varchar(2000) COLLATE Chinese_PRC_CI_AS NULL, slstRole varchar(500) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQXEdi__F530AB3F75CF74F4 PRIMARY KEY (QXID) );

CREATE TABLE GeneralExcel_DB.dbo.tabQXFormat ( QXID int NOT NULL, RepID int NOT NULL, slstOper varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQXFor__F530AB3F4DDF43A5 PRIMARY KEY (QXID) );

CREATE TABLE GeneralExcel_DB.dbo.tabQueryFA ( sFAName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, iFAID int NOT NULL, iOrd int NOT NULL, iRepID int NOT NULL, iTabID int NOT NULL, iTabType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sWhereSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sWhereSM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sQuerySQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sAdditionalWhereValue nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sAdditionalWhereSM nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sAdditionalQuerySQL nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, bPrivate char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iCreator int DEFAULT 0 NOT NULL, bForRep char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCount char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabQuerySQL ( QueryID int NOT NULL, sSQL text COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQuery__5967F7FBB17B2DE9 PRIMARY KEY (QueryID) );

CREATE TABLE GeneralExcel_DB.dbo.tabRLSetting ( RepID int NULL, FlowID int NULL, TaskID int NULL, TabID int NULL, ConditionsSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ConditionsSM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRepData ( DataID int NOT NULL, RepID int NOT NULL, FillDate datetime NOT NULL, ModifyDate datetime NOT NULL, DeptID int NOT NULL, OperID int NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iEndRow int NULL, iEndCol int NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iEditting varchar(50) COLLATE Chinese_PRC_CI_AS NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, CONSTRAINT PK__tabRepDa__9D05305DF6D6EAAE PRIMARY KEY (DataID) );

CREATE TABLE GeneralExcel_DB.dbo.tabRepDataB ( DataID int NOT NULL, BomID int NOT NULL, dDate datetime NOT NULL, DeptID int NOT NULL, OperID int NOT NULL, sBM nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS NULL, iEditting varchar(50) COLLATE Chinese_PRC_CI_AS NULL, F999991056 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991055 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991057 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, F999991058 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, F999991059 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabRepDa__9D05305DE5AD5E27 PRIMARY KEY (DataID) );

CREATE TABLE GeneralExcel_DB.dbo.tabRepData_Cross ( RepID int NOT NULL, DataID int NOT NULL, tabID int NOT NULL, iEndRow int NOT NULL, iEndCol int NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRepDetailTable ( RepID int NOT NULL, dtID int NOT NULL, tType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sheetName varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, ExpandDown char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ExpandRight char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, FlagForMulti char(1) COLLATE Chinese_PRC_CI_AS NULL, NoSaveData char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoProtectSheet char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sUniqueHint nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int DEFAULT 0 NOT NULL, QuickFill char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, AUI char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoDis char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoNull char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRepFormat ( RepID int NOT NULL, FID int NOT NULL, BeginDateTime datetime NOT NULL, EndDateTime datetime NOT NULL, RepFormat image NOT NULL, sSheetNames nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabRepFo__C1BEA5A20A674B27 PRIMARY KEY (FID) );

CREATE TABLE GeneralExcel_DB.dbo.tabRepGrid ( FID int NOT NULL, dtID int NOT NULL, FieldID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, iEndRow int NOT NULL, iEndCol int NOT NULL, iLayoutType int NOT NULL, SheetName varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRepPublish ( RepID int NOT NULL, DataID int NOT NULL, sCaption nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sURL nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, pubDate datetime NOT NULL, pubUser nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRepToolBtn ( RepID int NOT NULL, sFuncID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sName1 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName2 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName3 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, bFill int NULL, bEdit int NULL, bPost int NULL, bView int NULL, sMacro nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, sFlag varchar(20) COLLATE Chinese_PRC_CI_AS NULL, iBeginGroup int NULL, iDIY int NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRepToolBtnT ( sFuncID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sName1 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName2 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName3 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, bFill int NULL, bEdit int NULL, bPost int NULL, bView int NULL, sMacro nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, sFlag varchar(20) COLLATE Chinese_PRC_CI_AS NULL, iBeginGroup int NULL, iDIY int NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabReport ( RepID int NOT NULL, FID int NOT NULL, BM nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, CatID int NOT NULL, DetailTableID varchar(200) COLLATE Chinese_PRC_CI_AS NULL, bSaveData char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bSaveFile char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bRepShortcut char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, FillType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, CreateUser int NOT NULL, bCanSelAtView char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bSelExcelFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bOpenInputAfterLogin char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bDelDataNoConfirm char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMayResize char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bMayFormat char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bRuleCol char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bNoUsed char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoXSDetail char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanNull char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMenu char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, CONSTRAINT PK__tabRepor__2F6FA9ABE080A316 PRIMARY KEY (RepID) );

CREATE TABLE GeneralExcel_DB.dbo.tabReuseAutoBM ( RuleID int NOT NULL, getUser varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, getDate datetime NULL, sValue nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, iDataID int DEFAULT 0 NOT NULL, iFlag int DEFAULT 0 NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabRole ( RoleID int NOT NULL, sName nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sBM nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, bSel char(1) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabRole__8AFACE3A35CB6FF6 PRIMARY KEY (RoleID) );

CREATE TABLE GeneralExcel_DB.dbo.tabRoleOper ( RoleID int NOT NULL, OperID int NOT NULL, DeptID varchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iFlag char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabSMSRecv ( iID int NOT NULL, sPhone varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sSMS nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sFlag char(1) COLLATE Chinese_PRC_CI_AS NULL, bSended char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, dRecvDate datetime NULL, CONSTRAINT PK__tabSMSRe__DC512D72A1A46F6A PRIMARY KEY (iID) );

CREATE TABLE GeneralExcel_DB.dbo.tabSMSSended ( iID int NOT NULL, dSendDT datetime NULL, sPhone varchar(15) COLLATE Chinese_PRC_CI_AS NULL, sContent nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabSMSSe__DC512D72D54E6A6B PRIMARY KEY (iID) );

CREATE TABLE GeneralExcel_DB.dbo.tabSendOther ( iID int NOT NULL, sURL varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sData nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL, dDate datetime NULL, CONSTRAINT PK__tabSendO__DC512D72522A008E PRIMARY KEY (iID) );

CREATE TABLE GeneralExcel_DB.dbo.tabSessionM ( sLoginUser varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sOperLoginID varchar(50) COLLATE Chinese_PRC_CI_AS NULL, sValues nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabSessi__7F09644AAB40088F PRIMARY KEY (sLoginUser) );

CREATE TABLE GeneralExcel_DB.dbo.tabSheetNameCode ( RepID int NULL, sSheetName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sSheetCode varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabSrcTabRelation ( FormulaID int NOT NULL, TabID1 int NOT NULL, FieldID1 varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, LogicFlag varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, TabID2 int NOT NULL, FieldID2 varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, Flag char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabWX ( sOpenID varchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, OperID int NOT NULL, LoginName nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, sPWD varchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, sDB nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, dDate datetime NULL, CONSTRAINT PK__tabWX__A68D6874756E5ABD PRIMARY KEY (sOpenID) );

CREATE TABLE GeneralExcel_DB.dbo.tabWxMsgSended ( iID int NULL, F999991126 varchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991128 varchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991132 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, F999991136 datetime NULL, F999991138 datetime NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabXTCS ( CSMC varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, CSZ varchar(20) COLLATE Chinese_PRC_CI_AS NULL, SM varchar(30) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabXTCS__F5F078D509BA8015 PRIMARY KEY (CSMC) );

CREATE TABLE GeneralExcel_DB.dbo.tabXTOtherSetting ( iID int NOT NULL, sName nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, sSetting nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, sNameB nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, sNameC nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabXTOth__DC512D722BB73CDC PRIMARY KEY (iID) );

CREATE TABLE GeneralExcel_DB.dbo.tabXTPIC ( iFlag char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sUID varchar(30) COLLATE Chinese_PRC_CI_AS NULL, PicID int NULL, PicFile image NULL, CONSTRAINT PK__tabXTPIC__4C63E6097049A5FB PRIMARY KEY (iFlag) );

CREATE TABLE GeneralExcel_DB.dbo.tabXTPUBFMT ( fmt image NULL );

CREATE TABLE GeneralExcel_DB.dbo.tabXTSM ( SM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sSetting varchar(300) COLLATE Chinese_PRC_CI_AS NULL );