USE ReportServerTempDB;

CREATE TABLE ReportServerTempDB.dbo.ChunkData ( ChunkID uniqueidentifier NOT NULL, SnapshotDataID uniqueidentifier NOT NULL, ChunkFlags tinyint NULL, ChunkName nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, ChunkType int NULL, Version smallint NULL, MimeType nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Content image NULL, CONSTRAINT PK_ChunkData PRIMARY KEY (ChunkID) );

CREATE TABLE ReportServerTempDB.dbo.ChunkSegmentMapping ( ChunkId uniqueidentifier NOT NULL, SegmentId uniqueidentifier NOT NULL, StartByte bigint NOT NULL, LogicalByteCount int NOT NULL, ActualByteCount int NOT NULL, CONSTRAINT PK_ChunkSegmentMapping PRIMARY KEY (ChunkId, SegmentId) );

CREATE TABLE ReportServerTempDB.dbo.DBUpgradeHistory ( UpgradeID bigint IDENTITY(1, 1) NOT NULL, DbVersion nvarchar(25) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, [User] nvarchar(128) COLLATE Latin1_General_100_CI_AS_KS_WS DEFAULT suser_sname() NULL, [DateTime] datetime DEFAULT getdate() NULL, CONSTRAINT PK_DBUpgradeHistory PRIMARY KEY (UpgradeID) );

CREATE TABLE ReportServerTempDB.dbo.ExecutionCache ( ExecutionCacheID uniqueidentifier NOT NULL, ReportID uniqueidentifier NOT NULL, ExpirationFlags int NOT NULL, AbsoluteExpiration datetime NULL, RelativeExpiration int NULL, SnapshotDataID uniqueidentifier NOT NULL, LastUsedTime datetime DEFAULT getdate() NOT NULL, ParamsHash int DEFAULT 0 NOT NULL, CONSTRAINT PK_ExecutionCache PRIMARY KEY (ExecutionCacheID) );

CREATE TABLE ReportServerTempDB.dbo.PersistedStream ( SessionID varchar(32) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, [Index] int NOT NULL, Content image NULL, Name nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, MimeType nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Extension nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Encoding nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Error nvarchar(512) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, RefCount int NOT NULL, ExpirationDate datetime NOT NULL, CONSTRAINT PK_PersistedStream PRIMARY KEY (SessionID, [Index]) );

CREATE TABLE ReportServerTempDB.dbo.Segment ( SegmentId uniqueidentifier DEFAULT newsequentialid() NOT NULL, Content varbinary(MAX) NULL, CONSTRAINT PK_Segment PRIMARY KEY (SegmentId) );

CREATE TABLE ReportServerTempDB.dbo.SegmentedChunk ( ChunkId uniqueidentifier DEFAULT newsequentialid() NOT NULL, SnapshotDataId uniqueidentifier NOT NULL, ChunkFlags tinyint NOT NULL, ChunkName nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, ChunkType int NOT NULL, Version smallint NOT NULL, MimeType nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Machine nvarchar(512) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, SegmentedChunkId bigint IDENTITY(1, 1) NOT NULL, CONSTRAINT PK_SegmentedChunk PRIMARY KEY (SegmentedChunkId) );

CREATE TABLE ReportServerTempDB.dbo.SessionData ( SessionID varchar(32) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, CompiledDefinition uniqueidentifier NULL, SnapshotDataID uniqueidentifier NULL, IsPermanentSnapshot bit NULL, ReportPath nvarchar(464) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Timeout int NOT NULL, AutoRefreshSeconds int NULL, Expiration datetime NOT NULL, ShowHideInfo image NULL, DataSourceInfo image NULL, OwnerID uniqueidentifier NOT NULL, EffectiveParams ntext COLLATE Latin1_General_100_CI_AS_KS_WS NULL, CreationTime datetime NOT NULL, HasInteractivity bit NULL, SnapshotExpirationDate datetime NULL, HistoryDate datetime NULL, PageHeight float NULL, PageWidth float NULL, TopMargin float NULL, BottomMargin float NULL, LeftMargin float NULL, RightMargin float NULL, AwaitingFirstExecution bit NULL, EditSessionID varchar(32) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, DataSetInfo varbinary(MAX) NULL, SitePath nvarchar(440) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, SiteZone int DEFAULT 0 NOT NULL, ReportDefinitionPath nvarchar(464) COLLATE Latin1_General_100_CI_AS_KS_WS NULL );

CREATE TABLE ReportServerTempDB.dbo.SessionLock ( SessionID varchar(32) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, LockVersion int DEFAULT 0 NOT NULL );

CREATE TABLE ReportServerTempDB.dbo.SnapshotData ( SnapshotDataID uniqueidentifier NOT NULL, CreatedDate datetime NOT NULL, ParamsHash int NULL, QueryParams ntext COLLATE Latin1_General_100_CI_AS_KS_WS NULL, EffectiveParams ntext COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Description nvarchar(512) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, DependsOnUser bit NULL, PermanentRefcount int NOT NULL, TransientRefcount int NOT NULL, ExpirationDate datetime NOT NULL, PageCount int NULL, HasDocMap bit NULL, Machine nvarchar(512) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, PaginationMode smallint NULL, ProcessingFlags int NULL, IsCached bit DEFAULT 0 NULL );

CREATE TABLE ReportServerTempDB.dbo.TempCatalog ( EditSessionID varchar(32) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, TempCatalogID uniqueidentifier NOT NULL, ContextPath nvarchar(425) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, Name nvarchar(425) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, Content varbinary(MAX) NULL, Description nvarchar(MAX) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Intermediate uniqueidentifier NULL, IntermediateIsPermanent bit DEFAULT 0 NOT NULL, Property nvarchar(MAX) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, [Parameter] nvarchar(MAX) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, OwnerID uniqueidentifier NOT NULL, CreationTime datetime NOT NULL, ExpirationTime datetime NOT NULL, DataCacheHash varbinary(64) NULL, CONSTRAINT PK_TempCatalog PRIMARY KEY (EditSessionID, ContextPath), CONSTRAINT UNIQ_TempCatalogID UNIQUE (TempCatalogID) );

CREATE TABLE ReportServerTempDB.dbo.TempDataSets ( ID uniqueidentifier NOT NULL, ItemID uniqueidentifier NOT NULL, LinkID uniqueidentifier NULL, Name nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, CONSTRAINT PK_TempDataSet PRIMARY KEY (ID), CONSTRAINT FK_DataSetItemID FOREIGN KEY (ItemID) REFERENCES ReportServerTempDB.dbo.TempCatalog(TempCatalogID) );

CREATE TABLE ReportServerTempDB.dbo.TempDataSources ( DSID uniqueidentifier NOT NULL, ItemID uniqueidentifier NOT NULL, Name nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Extension nvarchar(260) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, Link uniqueidentifier NULL, CredentialRetrieval int NULL, Prompt ntext COLLATE Latin1_General_100_CI_AS_KS_WS NULL, ConnectionString image NULL, OriginalConnectionString image NULL, OriginalConnectStringExpressionBased bit NULL, UserName image NULL, Password image NULL, Flags int NULL, Version int NOT NULL, CONSTRAINT PK_DataSource PRIMARY KEY (DSID), CONSTRAINT FK_DataSourceItemID FOREIGN KEY (ItemID) REFERENCES ReportServerTempDB.dbo.TempCatalog(TempCatalogID) );