USE [供应链管理中心];

CREATE TABLE 供应链管理中心.dbo.tabAppPrint ( RepID int NOT NULL, PrintFormat nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabAppPr__2F6FA9AB9BE27510 PRIMARY KEY (RepID) );

CREATE TABLE 供应链管理中心.dbo.tabAutoBM ( RuleID int NULL, sFormat nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iSerial int NULL );

CREATE TABLE 供应链管理中心.dbo.tabAutoFill ( RepID int NOT NULL, sTimeSetting varchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sLastDoTime datetime NULL, DoDate datetime NULL, CONSTRAINT PK__tabAutoF__2F6FA9AB8F4C5CDE PRIMARY KEY (RepID) );

CREATE TABLE 供应链管理中心.dbo.tabBOMSDR ( bomID int NOT NULL, FieldID varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, DataRule int NULL, ExFillField varchar(200) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabBaseTableDataLocked ( tabID int NOT NULL, CONSTRAINT PK__tabBaseT__50656ECA2F8E7B92 PRIMARY KEY (tabID) );

CREATE TABLE 供应链管理中心.dbo.tabBom ( bomID int NOT NULL, sBM nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, iCreator int NOT NULL, bNMOther char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iMaxLevel int DEFAULT 0 NOT NULL, sColor varchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabBom__B6B08868467A14CE PRIMARY KEY (bomID) );

CREATE TABLE 供应链管理中心.dbo.tabBomNodeType ( bomID int NULL, iNodeTypeID int NULL, sDisplayField varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sMainFieldID int NULL, sLevelBMFieldID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sBOMIDFieldID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, slstFieldID varchar(600) COLLATE Chinese_PRC_CI_AS NULL, slstFieldName nvarchar(600) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabBomTree ( bomID int NULL, DataID int NULL, iNodeID int NULL, iNodeTypeID int NULL, sLevelNo varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sNodeName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsLeaf char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iFromDataID int DEFAULT 0 NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabCAdminR ( iID int NOT NULL, sValue char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iImageIndex int NOT NULL, RoleID int NOT NULL, iID2 int NOT NULL, iOrd int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabCancelTaskFormula ( RepID int NOT NULL, DataID int NOT NULL, sFormula text COLLATE Chinese_PRC_CI_AS NULL, sLinkID varchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabCategory ( CatID int NOT NULL, sName nvarchar(60) COLLATE Chinese_PRC_CI_AS NOT NULL, SJ int NULL, sBM nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabCateg__6A1C8ADAF1317EE4 PRIMARY KEY (CatID) );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable ( tabID int NOT NULL, tabName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, bBase int NULL, FormHeight int NULL, FormWidth int NULL, FormFormat image NULL, sOriTabName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sSchema nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDataFL varchar(300) COLLATE Chinese_PRC_CI_AS NULL, sDataOrd varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CatID int DEFAULT -1 NOT NULL, sBM varchar(30) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, sName2 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabDIYTa__50656ECA1A59D76B PRIMARY KEY (tabID) );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable0 ( F1 char(10) COLLATE Chinese_PRC_CI_AS NOT NULL, CONSTRAINT PK__tabDIYTa__321492706F0BB812 PRIMARY KEY (F1) );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable1 ( ID int NOT NULL, F1 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabDIYTa__3214EC279A152A3D PRIMARY KEY (ID) );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable10 ( ID int NOT NULL, iOrd int NOT NULL, F67 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F68 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F69 datetime DEFAULT '' NOT NULL, F71 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable11 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F72 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F73 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F74 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F90 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F91 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F92 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F93 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F94 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F95 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F96 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F97 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F98 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F99 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F100 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F101 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F102 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F103 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F104 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable13 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F116 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F117 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F118 datetime DEFAULT '' NOT NULL, F119 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable16 ( ID int NOT NULL, iOrd int NOT NULL, F376 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F377 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F378 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F379 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F380 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F381 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F382 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F383 datetime DEFAULT '' NOT NULL, F384 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F385 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F386 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable17 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F387 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F388 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F389 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F390 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F391 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F392 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F393 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F394 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F395 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F396 datetime DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable24 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F475 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F477 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F478 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F479 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F480 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F481 datetime DEFAULT '' NOT NULL, F482 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F483 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F488 nvarchar(1000) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F489 image NULL, F490 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F491 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F495 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F496 datetime DEFAULT '' NOT NULL, F497 datetime DEFAULT '' NOT NULL, F498 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F545 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable25 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F499 datetime DEFAULT '' NOT NULL, F500 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F501 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F502 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F503 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F504 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F505 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F506 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F507 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F508 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F509 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F510 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F511 datetime DEFAULT '' NOT NULL, F512 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F513 datetime DEFAULT '' NOT NULL, F514 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F515 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable26 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F516 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F532 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F536 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F537 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F538 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F539 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F540 datetime DEFAULT '' NOT NULL, F541 datetime DEFAULT '' NOT NULL, F542 datetime DEFAULT '' NOT NULL, F543 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F544 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable27 ( ID int NOT NULL, iOrd int NOT NULL, F524 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F525 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F526 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F527 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F528 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F529 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F530 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F531 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable29 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F546 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F547 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F548 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F549 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F550 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F551 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F552 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F553 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F554 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F555 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F556 datetime DEFAULT '' NOT NULL, F557 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F558 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F559 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F560 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F561 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F562 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F563 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F564 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F565 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F566 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F567 numeric(20, 0) DEFAULT 0 NOT NULL, F568 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F569 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F570 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F571 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F572 numeric(20, 0) DEFAULT 0 NOT NULL, F573 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F574 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F575 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F593 nvarchar(2) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F595 nvarchar(2) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F612 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F614 numeric(20, 2) DEFAULT 0 NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable32 ( ID int NOT NULL, iOrd int NOT NULL, F576 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F577 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F578 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F579 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F580 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F581 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F582 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F583 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F584 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F585 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F586 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F587 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F588 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F589 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable33 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F615 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F616 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F617 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F618 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F619 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F620 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F621 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F622 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F623 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F624 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F625 datetime DEFAULT '' NOT NULL, F626 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F627 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F628 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F629 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F630 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F631 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F632 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F633 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F634 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F635 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F636 numeric(20, 0) DEFAULT 0 NOT NULL, F637 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F638 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F639 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F640 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F641 numeric(20, 0) DEFAULT 0 NOT NULL, F642 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F643 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F644 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F645 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F647 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F648 numeric(20, 0) DEFAULT 0 NOT NULL, F714 nvarchar(1000) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F715 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F716 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F717 numeric(20, 0) DEFAULT 0 NOT NULL, F718 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable35 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F679 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F680 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F681 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F682 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F683 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F684 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F685 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F686 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F687 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F688 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F689 datetime DEFAULT '' NOT NULL, F690 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F691 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F692 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F693 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F694 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F695 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F696 nvarchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F697 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F698 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F699 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F700 numeric(20, 0) DEFAULT 0 NOT NULL, F701 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F702 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F703 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F704 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F705 numeric(20, 0) DEFAULT 0 NOT NULL, F706 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F707 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F708 nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F711 nvarchar(500) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F712 numeric(20, 0) DEFAULT 0 NOT NULL, F713 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable36 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F709 datetime DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable37 ( ID int NOT NULL, iOrd int NOT NULL, F710 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable4 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F4 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable6 ( ID int NOT NULL, iOrd int NOT NULL, F25 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F26 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F27 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F28 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F29 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F30 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F31 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F32 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F33 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F34 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F35 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F36 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F37 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F38 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F39 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F40 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F41 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F42 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F43 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F44 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable7 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F45 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable8 ( ID int NOT NULL, iOrd int NOT NULL, F46 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F47 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F48 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F49 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F50 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F51 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F52 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F53 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F54 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F55 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F56 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F57 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F58 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F59 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F60 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F61 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F62 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F63 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F64 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, F65 nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable9 ( ID int NOT NULL, iOrd int NOT NULL, RepID int DEFAULT 0 NOT NULL, FillDate datetime DEFAULT '' NOT NULL, ModifyDate datetime DEFAULT '' NOT NULL, DeptID int DEFAULT 0 NOT NULL, OperID int DEFAULT 0 NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, F66 datetime DEFAULT '' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable999998011 ( ID int NOT NULL, F999991001 varchar(3000) COLLATE Chinese_PRC_CI_AS NULL, F999991002 nvarchar(1500) COLLATE Chinese_PRC_CI_AS NULL, SendedDate datetime DEFAULT '' NOT NULL, F999991003 int DEFAULT 0 NOT NULL, F999991005 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable999998012 ( ID int NOT NULL, F999991011 varchar(200) COLLATE Chinese_PRC_CI_AS NULL, F999991012 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, F999991013 nvarchar(1500) COLLATE Chinese_PRC_CI_AS NULL, F999991015 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991016 int DEFAULT 0 NOT NULL, F999991017 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable999998036 ( ID int NOT NULL, F999991166 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991168 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTable999998038 ( iID int NULL, F999991126 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991128 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991132 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, F999991136 datetime NULL, F999991138 datetime NULL, F999991137 int DEFAULT 0 NOT NULL, F999991139 nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTableField ( tabID int NOT NULL, fieldID int NOT NULL, fieldName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iRow int NULL, iCol int NULL, TypeID int NOT NULL, bUnique char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bRequire char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bComboUnique char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, DataRule int NOT NULL, ParameterField varchar(500) COLLATE Chinese_PRC_CI_AS NULL, bNoClearData char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL, sOriFieldName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sOriFieldType varchar(50) COLLATE Chinese_PRC_CI_AS NULL, NoDisplay char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanKeyInput char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanSelAtRule char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bCanModifyAtFillDataWithFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bCanSelAtFillDataWithFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, ExFillField varchar(800) COLLATE Chinese_PRC_CI_AS NULL, bCanModifyExcelFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sLinkRepData ntext COLLATE Chinese_PRC_CI_AS NULL, sHintUnique nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sHintEmpty nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bAlwaysShowSelWin char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMerge char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sPicFileCon varchar(50) COLLATE Chinese_PRC_CI_AS NULL, bNF char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sCHK varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sName2 nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, sReferF int DEFAULT 0 NOT NULL, CONSTRAINT PK__tabDIYTa__F0AC27FE65316799 PRIMARY KEY (fieldID) );

CREATE TABLE 供应链管理中心.dbo.tabDIYTableFieldM ( NaviID int NOT NULL, ItemID int NOT NULL, tabID int NOT NULL, FieldID int NOT NULL, FieldName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sGroup nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bDisp int NOT NULL, bDigest int NOT NULL, iRowCount int NOT NULL, iOrd int NOT NULL, iOrd2 int NOT NULL, iColWidth int NULL );

CREATE TABLE 供应链管理中心.dbo.tabDIYTableFieldMW ( NaviID int NOT NULL, ItemID int NOT NULL, tabID int NOT NULL, iObjType int NOT NULL, FieldID int NOT NULL, FieldName nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sGroup nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bDisp int NOT NULL, bDigest int NOT NULL, iRowCount varchar(10) COLLATE Chinese_PRC_CI_AS NOT NULL, iMargin int NOT NULL, iRow int NOT NULL, iRWidth int NOT NULL, iRMargin int NOT NULL, iLabPos int NOT NULL, sLabWidth varchar(10) COLLATE Chinese_PRC_CI_AS NULL, sHint nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iTouch int NULL, sParam nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NOT NULL, iOrd2 int NOT NULL, sTotal nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, iColWidth int NULL, iCard int DEFAULT 0 NULL, iNC int DEFAULT 0 NULL );

CREATE TABLE 供应链管理中心.dbo.tabDV ( iID int NULL, sName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iOperType int NOT NULL, iObjType int NOT NULL, iObjID int NOT NULL, iRepID int NOT NULL, iCreator int NOT NULL, iUser int NOT NULL, bDefault char(1) COLLATE Chinese_PRC_CI_AS NULL, bCanEdit char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDVs ( iID int NOT NULL, iUser int NOT NULL, TabID int NOT NULL, FieldID varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, bVisible char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iWidth int NOT NULL, sTotal nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, bSys char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDataRule ( RuleID int NOT NULL, RuleName nvarchar(60) COLLATE Chinese_PRC_CI_AS NOT NULL, RuleType int NOT NULL, DataSrc char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, MultiSel char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, OnlyLeaf char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bOrigin char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, bUnique char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bReFresh char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMayNULL char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoAutoFit char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iCreator int DEFAULT 0 NOT NULL, bNMOther char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bFOBO char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sSize varchar(20) COLLATE Chinese_PRC_CI_AS NULL, bQuery char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sDisN varchar(40) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int DEFAULT 0 NULL, CONSTRAINT PK__tabDataR__110458C24EAA499A PRIMARY KEY (RuleID) );

CREATE TABLE 供应链管理中心.dbo.tabDataRuleCategory ( CatID int NOT NULL, sName nvarchar(25) COLLATE Chinese_PRC_CI_AS NOT NULL, SJ int NOT NULL, sNameB nvarchar(25) COLLATE Chinese_PRC_CI_AS NULL, sNameC nvarchar(25) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabDataR__6A1C8ADAE9373087 PRIMARY KEY (CatID) );

CREATE TABLE 供应链管理中心.dbo.tabDataRules1 ( RuleID int NOT NULL, ValueID int NOT NULL, SubValue nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, LevelValue varchar(30) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDataRules2 ( RuleID int NOT NULL, tabIDName varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, DisplayField varchar(500) COLLATE Chinese_PRC_CI_AS NOT NULL, ConditionNames ntext COLLATE Chinese_PRC_CI_AS NULL, LevelField nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, LevelLen varchar(30) COLLATE Chinese_PRC_CI_AS NULL, OrdField varchar(150) COLLATE Chinese_PRC_CI_AS NULL, bIsDESC varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, ValueFieldIndex int DEFAULT 0 NOT NULL, sCategory varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sTree3 varchar(200) COLLATE Chinese_PRC_CI_AS NULL, NDispF varchar(500) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(300) COLLATE Chinese_PRC_CI_AS NULL, ConditionIDs ntext COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabDataRules3 ( RuleID int NOT NULL, HeadTitle nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL, DateFormat varchar(8) COLLATE Chinese_PRC_CI_AS NULL, SerialLen int NULL, StartValue int NULL, ResetAfterDateChange char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, DateValue varchar(8) COLLATE Chinese_PRC_CI_AS NULL, SerialValue int NULL, ActionAfterSave char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, ReuseType char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, TitleAfterDate varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sFormat nvarchar(100) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, sFormatSetting nvarchar(150) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, NFN char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabDataSrcOther ( srcID int NOT NULL, srcName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sAccessPrefix nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sProvider varchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDataSrc nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDBName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sLoginUser nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sPassword varchar(30) COLLATE Chinese_PRC_CI_AS NULL, bCanModify char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, CONSTRAINT PK__tabDataS__5DD08E2FD18A0139 PRIMARY KEY (srcID) );

CREATE TABLE 供应链管理中心.dbo.tabDataType ( TypeID int NOT NULL, TypeName nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, OriginType varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, iLen int NOT NULL, iXSLen int NULL, sDefault varchar(20) COLLATE Chinese_PRC_CI_AS NULL, MatchWord nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, iOrd int DEFAULT 0 NULL, CONSTRAINT PK__tabDataT__516F039571B67E14 PRIMARY KEY (TypeID) );

CREATE TABLE 供应链管理中心.dbo.tabDepartment ( DeptID int NOT NULL, sName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, BM nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, SJ int NOT NULL, FZJG char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, CONSTRAINT PK__tabDepar__0148818E6940D218 PRIMARY KEY (DeptID) );

CREATE TABLE 供应链管理中心.dbo.tabEMAILSended ( iID int NOT NULL, dSendDT datetime NULL, sAddress varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sSubject nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sContent nvarchar(1500) COLLATE Chinese_PRC_CI_AS NULL, sAttchFile nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabEMAIL__DC512D7291DD6C07 PRIMARY KEY (iID) );

CREATE TABLE 供应链管理中心.dbo.tabEntFlow ( EntFlowID int NOT NULL, bUse char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, date1 datetime NOT NULL, date2 datetime NOT NULL, iAfter int DEFAULT 0 NOT NULL, FlowID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, OperID1 int NOT NULL, OperID2 varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabEntFl__DCE624BDADFE22C9 PRIMARY KEY (EntFlowID) );

CREATE TABLE 供应链管理中心.dbo.tabEnterprise ( EnterID int NOT NULL, sName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, Address nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, PostNo varchar(20) COLLATE Chinese_PRC_CI_AS NULL, Tel varchar(20) COLLATE Chinese_PRC_CI_AS NULL, Fex varchar(20) COLLATE Chinese_PRC_CI_AS NULL, email varchar(30) COLLATE Chinese_PRC_CI_AS NULL, www varchar(100) COLLATE Chinese_PRC_CI_AS NULL, Bank nvarchar(60) COLLATE Chinese_PRC_CI_AS NULL, CountNo varchar(30) COLLATE Chinese_PRC_CI_AS NULL, TaxNo varchar(30) COLLATE Chinese_PRC_CI_AS NULL, CheckDay int NULL, CONSTRAINT PK__tabEnter__74B398146D2438D4 PRIMARY KEY (EnterID) );

CREATE TABLE 供应链管理中心.dbo.tabFTPPicFile ( RepID int NOT NULL, DataID int NOT NULL, sFileName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFillRule ( FormulaID int NOT NULL, TabID int NOT NULL, SrcFieldSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, SrcFieldSM nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL, FillType int NOT NULL, TargetFieldID int NOT NULL, iOrd int NOT NULL, sQryFName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sFlag char(1) COLLATE Chinese_PRC_CI_AS NULL, sTotal nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, iOrd2 int DEFAULT 0 NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlow ( flowID int NOT NULL, RepID int NOT NULL, flowCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, bValidate char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, chart image NOT NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, PauseField varchar(20) COLLATE Chinese_PRC_CI_AS NULL, [NoLock] char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sSubject nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sFormula varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, bNotInNoF int DEFAULT 0 NOT NULL, CONSTRAINT PK__tabFlow__A94CE37D087A3660 PRIMARY KEY (flowID) );

CREATE TABLE 供应链管理中心.dbo.tabFlowLink ( FlowID int NOT NULL, LinkID varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, BeginTaskID int NOT NULL, EndTaskID int NOT NULL, bNewRep char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NewRepID int NULL, ConditionType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ConditionsSQL ntext COLLATE Chinese_PRC_CI_AS NULL, ConditionsSM ntext COLLATE Chinese_PRC_CI_AS NULL, lstFormulaID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, sHint nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, NewRepFirstDoUser varchar(200) COLLATE Chinese_PRC_CI_AS DEFAULT '0,0' NOT NULL, sClearFieldP varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sClearFieldB varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sFillField varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, bAsBack char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, DoUser char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, lstDeptID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, lstRoleID varchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowMS ( FlowID int NULL, FlowPostID int NULL, DataID int NULL, taskID int NULL, iOrd numeric(13, 4) NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sSubject nvarchar(600) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowPost ( RepID int NOT NULL, FlowID int NOT NULL, FlowPostID int NOT NULL, DataID int NOT NULL, taskID int NOT NULL, DoTime datetime NOT NULL, DoUser int NOT NULL, iOrd numeric(20, 4) NOT NULL, iState smallint NOT NULL, DoingUser int NOT NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iHA int DEFAULT 0 NOT NULL, iHAValues nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, iDoLevel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iSub int DEFAULT 0 NOT NULL, DoTime1 datetime DEFAULT '0' NOT NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowPostF ( RepID int NOT NULL, FlowID int NOT NULL, FlowPostID int NOT NULL, DataID int NOT NULL, taskID int NOT NULL, DoTime datetime NOT NULL, DoUser int NOT NULL, iOrd numeric(20, 4) NOT NULL, iState smallint NOT NULL, DoingUser int NOT NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iHA int DEFAULT 0 NOT NULL, iHAValues nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, iDoLevel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iSub int DEFAULT 0 NOT NULL, DoTime1 datetime DEFAULT '0' NOT NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowPostS ( RepID int NOT NULL, FlowID int NOT NULL, FlowPostID int NOT NULL, DataID int NOT NULL, taskID int NOT NULL, DoTime datetime NOT NULL, DoUser int NOT NULL, iOrd numeric(20, 4) NOT NULL, iState smallint NOT NULL, DoingUser int NOT NULL, ToDoUsers varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoDepts varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ToDoRoles varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sDesc nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, iHA int DEFAULT 0 NOT NULL, iHAValues nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, HasHintTime datetime NULL, sSubject nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, iDoLevel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iSub int DEFAULT 0 NOT NULL, DoTime1 datetime DEFAULT '0' NOT NULL, sSubject2 nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowTask ( flowID int NOT NULL, taskID int NOT NULL, taskCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, bSaveDataAfterFinish char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bIsMustDoBeforeTime char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, MustDoBeforeTime int NOT NULL, TimeUnit char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, DoUser varchar(3) COLLATE Chinese_PRC_CI_AS NULL, ExeType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, lstFormulaID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, FillArea varchar(3500) COLLATE Chinese_PRC_CI_AS NULL, lstDeptID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, lstRoleID varchar(500) COLLATE Chinese_PRC_CI_AS NULL, bCanViewAfterDo char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sHintSet varchar(100) COLLATE Chinese_PRC_CI_AS NULL, bUseEMail char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bUseSMS char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoVisiArea varchar(1500) COLLATE Chinese_PRC_CI_AS NULL, NoPause char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoPrior varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, NoCancel char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoCheck char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanTran varchar(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOther varchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowTaskHAL ( FlowID int NOT NULL, FlowPostID int NOT NULL, iTime int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabFlowTaskRuleForNewRepFlow ( FlowID int NOT NULL, LinkID varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, srcRepTable int NOT NULL, srcFieldID int NOT NULL, FillType varchar(10) COLLATE Chinese_PRC_CI_AS NOT NULL, destRepTable int NOT NULL, destFieldID int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabFormula ( RepID int NOT NULL, FormulaID int NOT NULL, FormulaName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, FormulaType int NOT NULL, ExeTime varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL, UseShortCut char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ClearFillRange char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ResultIsUnique char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, OrdType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, SrcTabID varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, SelTemp char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NULL, bSomeData char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, SomeRecords int DEFAULT 0 NOT NULL, bAppendData char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sWhereSQL2 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sWhereSM2 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, bIncludeNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sHintYes nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sHintNo nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, ResultAction char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoDisplayTextWhenApply char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bDelNullRowAfterExecute char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sToDoUser varchar(200) COLLATE Chinese_PRC_CI_AS NULL, bReFreshSheet char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoCheckRelation char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bAppendWhenNoMatch char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOrderAfterExec varchar(30) COLLATE Chinese_PRC_CI_AS NULL, sMergeField varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, bUnMerge char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoFill0 char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bShowWait char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, ReserveRowCol int DEFAULT 0 NOT NULL, iVer int DEFAULT 0 NOT NULL, sSysRule varchar(200) COLLATE Chinese_PRC_CI_AS NULL, bDSOther char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iMPP char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoAuto char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL3 ntext COLLATE Chinese_PRC_CI_AS NULL, sWhereSM3 ntext COLLATE Chinese_PRC_CI_AS NULL, FormulaSM ntext COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL ntext COLLATE Chinese_PRC_CI_AS NULL, sWhereSM ntext COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabFormulaGrid ( FID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabFormulaWithSSFunction ( FID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, sFormula nvarchar(500) COLLATE Chinese_PRC_CI_AS NOT NULL, SheetName nvarchar(80) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabFunction ( CatID int NOT NULL, CatName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, Flag char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iOrd int NULL, CONSTRAINT PK__tabFunct__9C61AB2794C75772 PRIMARY KEY (CatName) );

CREATE TABLE 供应链管理中心.dbo.tabFunctions ( CatID int NOT NULL, FuncName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, FuncSQL varchar(130) COLLATE Chinese_PRC_CI_AS NOT NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NOT NULL, CONSTRAINT PK__tabFunct__10105C800C1459B5 PRIMARY KEY (FuncName) );

CREATE TABLE 供应链管理中心.dbo.tabGVar ( iID int NOT NULL, sVarName nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sVarValue nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabGridFormat ( RepID int NOT NULL, DataID int NOT NULL, tabID int NOT NULL, FieldID int NOT NULL, iRow int DEFAULT 0 NOT NULL, iCol int DEFAULT 0 NOT NULL, iRowCount int DEFAULT 0 NOT NULL, iColCount int DEFAULT 0 NOT NULL, sSetting nvarchar(300) COLLATE Chinese_PRC_CI_AS NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabGridTextOfFormat ( FID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, sText nvarchar(500) COLLATE Chinese_PRC_CI_AS NOT NULL, SheetName nvarchar(80) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabHyperLinks ( RepID int NOT NULL, DataID int NOT NULL, TabID int NOT NULL, FieldID int NOT NULL, iRelativeRow int NOT NULL, iRelativeCol int NOT NULL, sFileName nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, fFile image NOT NULL, sLinkNo varchar(20) COLLATE Chinese_PRC_CI_AS NULL, bFTP char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabInnerTableCode ( iTabID int NOT NULL, sCode text COLLATE Chinese_PRC_CI_AS NULL, iFormulaID int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabLockRepDataFormula ( RepID int NOT NULL, sFormulaSM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sFormulaSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, bUnLock char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bOnlyThis char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, CONSTRAINT PK__tabLockR__2F6FA9AB7DF5AD63 PRIMARY KEY (RepID) );

CREATE TABLE 供应链管理中心.dbo.tabLog ( OperUserName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, OperTime varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, sIP nvarchar(150) COLLATE Chinese_PRC_CI_AS NOT NULL, FuncName nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, SM nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabLoginByOther ( bActived char(1) COLLATE Chinese_PRC_CI_AS NULL, sURL nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sUser nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sPwd varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sResult nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sResultValue nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL, sMsg nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabLoginInfo ( sLoginUser varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sLoginName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sLoginIP nvarchar(150) COLLATE Chinese_PRC_CI_AS NULL, tLoginTime datetime NULL, iOnlineMinute int NULL, InterLoginID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sDBName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sLocalIPAndName nvarchar(150) COLLATE Chinese_PRC_CI_AS NULL, sLoginUser2 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabLoginLog ( OperID int NOT NULL, ChPWDateTime datetime NULL, LockTime datetime NULL, sLastPW text COLLATE Chinese_PRC_CI_AS NULL, sPWErrLog ntext COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabLogin__F288E41D5C9D0A8B PRIMARY KEY (OperID) );

CREATE TABLE 供应链管理中心.dbo.tabMFValues ( RepID int NOT NULL, DataID int NOT NULL, TabID int NOT NULL, FieldID int NOT NULL, iOrd int NOT NULL, sValue nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabNULL ( a1 char(1) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabNaviItem ( ItemID int NOT NULL, NaviID int NOT NULL, sCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iAction int NOT NULL, iObj int NOT NULL, iOrd int NOT NULL, imgIcon image NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, iFlowID int DEFAULT 0 NULL, CONSTRAINT PK__tabNaviI__727E83EB65C4EF8F PRIMARY KEY (ItemID) );

CREATE TABLE 供应链管理中心.dbo.tabNaviM ( NaviID int NOT NULL, NaviCaption nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, iOrd int NOT NULL, iFlag int DEFAULT 0 NOT NULL, sVer varchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NaviBM varchar(20) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabNaviM__2F08BDA8C2A58981 PRIMARY KEY (NaviID) );

CREATE TABLE 供应链管理中心.dbo.tabNavigate ( NaviID int NOT NULL, NaviBM nvarchar(20) COLLATE Chinese_PRC_CI_AS NULL, NaviCaption nvarchar(80) COLLATE Chinese_PRC_CI_AS NULL, NaviVer varchar(20) COLLATE Chinese_PRC_CI_AS NULL, DisTab varchar(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NaviPic image NULL, NaviIcon image NULL, TopTab char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCheckQX char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabNavig__2F08BDA8488AC31A PRIMARY KEY (NaviID) );

CREATE TABLE 供应链管理中心.dbo.tabNoVF ( FID int NOT NULL, dtID int NOT NULL, FieldID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, iEndRow int NOT NULL, iEndCol int NOT NULL, iLayoutType int NOT NULL, SheetName nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabObjDoing ( iObjType int NULL, iObjID int NULL, iOperID int NULL, sOperName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, dOperDate datetime NULL );

CREATE TABLE 供应链管理中心.dbo.tabOperator ( OperID int NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, DeptID int NOT NULL, LoginName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, LoginPassword varchar(200) COLLATE Chinese_PRC_CI_AS NULL, Mobile varchar(20) COLLATE Chinese_PRC_CI_AS NULL, email varchar(100) COLLATE Chinese_PRC_CI_AS NULL, SJType int NOT NULL, SJDepartment int NULL, SJRole int NULL, SJOperator int NULL, BZ1 char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, SM nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sIP varchar(100) COLLATE Chinese_PRC_CI_AS NULL, bLock char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sDeptAdmin varchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, bMLog char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoChPW char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sLogF varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, sOrd nvarchar(50) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, CONSTRAINT PK__tabOpera__F288E41D266237E7 PRIMARY KEY (OperID) );

CREATE TABLE 供应链管理中心.dbo.tabOption ( OperID int NOT NULL, OptionName varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, OptionValue varchar(30) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabOtherSrcTable ( tabID int NOT NULL, sPrefix nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, sStruct ntext COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabOther__50656ECA6BBC6A1B PRIMARY KEY (tabID) );

CREATE TABLE 供应链管理中心.dbo.tabPZ ( RepID int NOT NULL, DataID int NOT NULL, tabID int NOT NULL, FieldID int NOT NULL, iRow int NULL, iCol int NULL, sPZ nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabPrintSetting ( RepID int NOT NULL, bSave char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bFinish char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bConField char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sField varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sMsg nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iPrtTimes int DEFAULT 0 NOT NULL, sMsgT nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabPrint__2F6FA9AB4384DBF7 PRIMARY KEY (RepID) );

CREATE TABLE 供应链管理中心.dbo.tabPrtLog ( RepID int NULL, DataID int NULL, sLoginName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sDateTime datetime NULL );

CREATE TABLE 供应链管理中心.dbo.tabQX ( ObjID int NOT NULL, lstDeptID varchar(3000) COLLATE Chinese_PRC_CI_AS NULL, lstRoleID varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, lstOperID varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, QXType int NOT NULL, ObjType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabQX1 ( QXID int NOT NULL, ObjID int NOT NULL, iDeptID int NOT NULL, iRoleID int NOT NULL, iOperID int NOT NULL, QXType int NOT NULL, ObjType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, NoVisibleFieldIDs varchar(3000) COLLATE Chinese_PRC_CI_AS NULL, QXTypeByContent char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, QXField varchar(20) COLLATE Chinese_PRC_CI_AS NULL, QXType2 int DEFAULT 0 NOT NULL, QXConst nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sWhereSM nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sWhereSQL2 nvarchar(700) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQX1__F530AB3F01EF9E3A PRIMARY KEY (QXID) );

CREATE TABLE 供应链管理中心.dbo.tabQX2 ( QXID int NOT NULL, RepID int NOT NULL, TabID int NOT NULL, iDeptID int NOT NULL, iRoleID int NOT NULL, iOperID int NOT NULL, CONSTRAINT PK__tabQX2__F530AB3F7BA524E0 PRIMARY KEY (QXID) );

CREATE TABLE 供应链管理中心.dbo.tabQX3 ( QXID int NOT NULL, ObjID int NOT NULL, iDeptID int NOT NULL, iRoleID int NOT NULL, QXType int NOT NULL, ManageType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, CONSTRAINT PK__tabQX3__F530AB3F934774B9 PRIMARY KEY (QXID) );

CREATE TABLE 供应链管理中心.dbo.tabQXEdit ( QXID int NOT NULL, ObjID int NOT NULL, bOnlyMe char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bMe char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bNoMe char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bOther char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, slstOtherOper varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ObjType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, slstDept varchar(2000) COLLATE Chinese_PRC_CI_AS NULL, slstRole varchar(500) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQXEdi__F530AB3F4D6738A7 PRIMARY KEY (QXID) );

CREATE TABLE 供应链管理中心.dbo.tabQXFormat ( QXID int NOT NULL, RepID int NOT NULL, slstOper varchar(1000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQXFor__F530AB3F70FB33A8 PRIMARY KEY (QXID) );

CREATE TABLE 供应链管理中心.dbo.tabQueryFA ( sFAName nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, iFAID int NOT NULL, iOrd int NOT NULL, iRepID int NOT NULL, iTabID int NOT NULL, iTabType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sWhereSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sWhereSM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sQuerySQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NOT NULL, sAdditionalWhereValue nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sAdditionalWhereSM nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sAdditionalQuerySQL nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, bPrivate char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iCreator int DEFAULT 0 NOT NULL, bForRep char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCount char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabQuerySQL ( QueryID int NOT NULL, sSQL text COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabQuery__5967F7FB01122C16 PRIMARY KEY (QueryID) );

CREATE TABLE 供应链管理中心.dbo.tabRLSetting ( RepID int NULL, FlowID int NULL, TaskID int NULL, TabID int NULL, ConditionsSQL nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, ConditionsSM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL );

CREATE TABLE 供应链管理中心.dbo.tabRepData ( DataID int NOT NULL, RepID int NOT NULL, FillDate datetime NOT NULL, ModifyDate datetime NOT NULL, DeptID int NOT NULL, OperID int NOT NULL, sDesc nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iEndRow int NULL, iEndCol int NULL, bIsFinish char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bCanViewWhenNoFinished char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iEditting varchar(50) COLLATE Chinese_PRC_CI_AS NULL, OperID2 int DEFAULT '0' NOT NULL, dUpdate2 datetime NULL, CONSTRAINT PK__tabRepDa__9D05305D8D194950 PRIMARY KEY (DataID) );

CREATE TABLE 供应链管理中心.dbo.tabRepDataB ( DataID int NOT NULL, BomID int NOT NULL, dDate datetime NOT NULL, DeptID int NOT NULL, OperID int NOT NULL, sBM nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS NULL, iEditting varchar(50) COLLATE Chinese_PRC_CI_AS NULL, F999991056 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991055 nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991057 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, F999991058 nvarchar(50) COLLATE Chinese_PRC_CI_AS NULL, F999991059 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabRepDa__9D05305D24E53F4A PRIMARY KEY (DataID) );

CREATE TABLE 供应链管理中心.dbo.tabRepData_Cross ( RepID int NOT NULL, DataID int NOT NULL, tabID int NOT NULL, iEndRow int NOT NULL, iEndCol int NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabRepDetailTable ( RepID int NOT NULL, dtID int NOT NULL, tType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sheetName varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, ExpandDown char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, ExpandRight char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, FlagForMulti char(1) COLLATE Chinese_PRC_CI_AS NULL, NoSaveData char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoProtectSheet char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, sUniqueHint nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int DEFAULT 0 NOT NULL, QuickFill char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, AUI char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, NoDis char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoNull char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabRepFormat ( RepID int NOT NULL, FID int NOT NULL, BeginDateTime datetime NOT NULL, EndDateTime datetime NOT NULL, RepFormat image NOT NULL, sSheetNames nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sOther varchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabRepFo__C1BEA5A2BAD42BAD PRIMARY KEY (FID) );

CREATE TABLE 供应链管理中心.dbo.tabRepGrid ( FID int NOT NULL, dtID int NOT NULL, FieldID int NOT NULL, iRow int NOT NULL, iCol int NOT NULL, iEndRow int NOT NULL, iEndCol int NOT NULL, iLayoutType int NOT NULL, SheetName varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabRepPublish ( RepID int NOT NULL, DataID int NOT NULL, sCaption nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sURL nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, pubDate datetime NOT NULL, pubUser nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabRepToolBtn ( RepID int NOT NULL, sFuncID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sName1 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName2 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName3 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, bFill int NULL, bEdit int NULL, bPost int NULL, bView int NULL, sMacro nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, sFlag varchar(20) COLLATE Chinese_PRC_CI_AS NULL, iBeginGroup int NULL, iDIY int NULL );

CREATE TABLE 供应链管理中心.dbo.tabRepToolBtnT ( sFuncID varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sName1 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName2 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, sName3 nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, bFill int NULL, bEdit int NULL, bPost int NULL, bView int NULL, sMacro nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, sFlag varchar(20) COLLATE Chinese_PRC_CI_AS NULL, iBeginGroup int NULL, iDIY int NULL );

CREATE TABLE 供应链管理中心.dbo.tabReport ( RepID int NOT NULL, FID int NOT NULL, BM nvarchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, sName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, CatID int NOT NULL, DetailTableID varchar(200) COLLATE Chinese_PRC_CI_AS NULL, bSaveData char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bSaveFile char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, bRepShortcut char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, FillType char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, CreateUser int NOT NULL, bCanSelAtView char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bSelExcelFormula char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bLocked char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bOpenInputAfterLogin char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bDelDataNoConfirm char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMayResize char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bMayFormat char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bRuleCol char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '1' NOT NULL, bNoUsed char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bNoXSDetail char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bCanNull char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, bMenu char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, CONSTRAINT PK__tabRepor__2F6FA9ABA84701FF PRIMARY KEY (RepID) );

CREATE TABLE 供应链管理中心.dbo.tabReuseAutoBM ( RuleID int NOT NULL, getUser varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, getDate datetime NULL, sValue nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, iDataID int DEFAULT 0 NOT NULL, iFlag int DEFAULT 0 NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabRole ( RoleID int NOT NULL, sName nvarchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, sDesc nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, NotUsed char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sBM nvarchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '' NOT NULL, bSel char(1) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabRole__8AFACE3A3F39E6A7 PRIMARY KEY (RoleID) );

CREATE TABLE 供应链管理中心.dbo.tabRoleOper ( RoleID int NOT NULL, OperID int NOT NULL, DeptID varchar(20) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, iFlag char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabSMSRecv ( iID int NOT NULL, sPhone varchar(20) COLLATE Chinese_PRC_CI_AS NULL, sSMS nvarchar(500) COLLATE Chinese_PRC_CI_AS NULL, sFlag char(1) COLLATE Chinese_PRC_CI_AS NULL, bSended char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL, dRecvDate datetime NULL, CONSTRAINT PK__tabSMSRe__DC512D72B1F0ADB5 PRIMARY KEY (iID) );

CREATE TABLE 供应链管理中心.dbo.tabSMSSended ( iID int NOT NULL, dSendDT datetime NULL, sPhone varchar(15) COLLATE Chinese_PRC_CI_AS NULL, sContent nvarchar(100) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabSMSSe__DC512D72084D3B22 PRIMARY KEY (iID) );

CREATE TABLE 供应链管理中心.dbo.tabSendOther ( iID int NOT NULL, sURL varchar(200) COLLATE Chinese_PRC_CI_AS NULL, sData nvarchar(2000) COLLATE Chinese_PRC_CI_AS NULL, dDate datetime NULL, CONSTRAINT PK__tabSendO__DC512D72B59961CB PRIMARY KEY (iID) );

CREATE TABLE 供应链管理中心.dbo.tabSessionM ( sLoginUser varchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, sOperLoginID varchar(50) COLLATE Chinese_PRC_CI_AS NULL, sValues nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabSessi__7F09644A94402C8E PRIMARY KEY (sLoginUser) );

CREATE TABLE 供应链管理中心.dbo.tabSheetNameCode ( RepID int NULL, sSheetName nvarchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, sSheetCode varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabSrcTabRelation ( FormulaID int NOT NULL, TabID1 int NOT NULL, FieldID1 varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, LogicFlag varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, TabID2 int NOT NULL, FieldID2 varchar(20) COLLATE Chinese_PRC_CI_AS NOT NULL, Flag char(1) COLLATE Chinese_PRC_CI_AS DEFAULT '0' NOT NULL );

CREATE TABLE 供应链管理中心.dbo.tabWX ( sOpenID varchar(100) COLLATE Chinese_PRC_CI_AS NOT NULL, OperID int NOT NULL, LoginName nvarchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, sPWD varchar(200) COLLATE Chinese_PRC_CI_AS NOT NULL, sDB nvarchar(50) COLLATE Chinese_PRC_CI_AS NOT NULL, dDate datetime NULL, CONSTRAINT PK__tabWX__A68D68742DEAC9A2 PRIMARY KEY (sOpenID) );

CREATE TABLE 供应链管理中心.dbo.tabWxMsgSended ( iID int NULL, F999991126 varchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991128 varchar(100) COLLATE Chinese_PRC_CI_AS NULL, F999991132 nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, F999991136 datetime NULL, F999991138 datetime NULL );

CREATE TABLE 供应链管理中心.dbo.tabXTCS ( CSMC varchar(30) COLLATE Chinese_PRC_CI_AS NOT NULL, CSZ varchar(20) COLLATE Chinese_PRC_CI_AS NULL, SM varchar(30) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabXTCS__F5F078D5AC8FADA5 PRIMARY KEY (CSMC) );

CREATE TABLE 供应链管理中心.dbo.tabXTOtherSetting ( iID int NOT NULL, sName nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, sSetting nvarchar(200) COLLATE Chinese_PRC_CI_AS NULL, iOrd int NULL, sNameB nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, sNameC nvarchar(30) COLLATE Chinese_PRC_CI_AS NULL, CONSTRAINT PK__tabXTOth__DC512D72B150136A PRIMARY KEY (iID) );

CREATE TABLE 供应链管理中心.dbo.tabXTPIC ( iFlag char(1) COLLATE Chinese_PRC_CI_AS NOT NULL, sUID varchar(30) COLLATE Chinese_PRC_CI_AS NULL, PicID int NULL, PicFile image NULL, CONSTRAINT PK__tabXTPIC__4C63E609E396BE84 PRIMARY KEY (iFlag) );

CREATE TABLE 供应链管理中心.dbo.tabXTPUBFMT ( fmt image NULL );

CREATE TABLE 供应链管理中心.dbo.tabXTSM ( SM nvarchar(1000) COLLATE Chinese_PRC_CI_AS NULL, sSetting varchar(300) COLLATE Chinese_PRC_CI_AS NULL );