FROM mcr.microsoft.com/mssql/server:2017-latest

# 设置 SA 密码和接受许可协议
ENV SA_PASSWORD=Swq8855830.
ENV ACCEPT_EULA=Y

# 创建初始化脚本目录
USER root
RUN mkdir -p /init-sql

# 拷贝 SQL 脚本到容器
COPY *.sql /init-sql/

# 新增执行脚本
COPY entrypoint.sh /init-sql/
RUN chmod +x /init-sql/entrypoint.sh

# 启动 SQL Server 并执行初始化脚本
RUN /init-sql/entrypoint.sh

EXPOSE 1433