FROM mysql:9.3.0-oraclelinux9

ENV MYSQL_ROOT_PASSWORD=Swq8855830.

COPY 0_init.sql /docker-entrypoint-initdb.d/
COPY 1_data.sql /docker-entrypoint-initdb.d/

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD mysql -h localhost -u root -p${MYSQL_ROOT_PASSWORD} -e "SELECT * FROM zj_itsm.st_target_data_excel_copy1" || exit 1

EXPOSE 3306